"""
DO NOT MANUALLY RUN THIS SCRIPT.
---------------------------------

This script is designed to generate and push a CL file that can be later compiled.
The body of the changelog is determined by the description of the PR that was merged.

If a commit is pushed without being associated with a PR, or if a PR is missing a CL,
the script is designed to exit as a failure. This is to help keep track of PRs without
CLs and direct commits. See the relating comments in the below source to disable this function.

This script depends on the tags.yml file located in the same directory. You can use that
file to configure the exact tags you'd like this script to use when generating changelog entries.
If this is being used in a /tg/ or Bee downstream, the default tags should work.

Expected envrionmental variables:
-----------------------------------
GIT_NAME: Username of the github account to be used as the commited (User provided)
GIT_EMAIL: Email associated with the above (User provided)
GITHUB_REPOSITORY: Github action variable representing the active repo (Action provided)
GITHUB_TOKEN: A snowflake token generated by the action, this will allow the action to push the changes (User provided, action generated)
GITHUB_SHA: The SHA associated with the commit that triggered the action (Action provided)
"""
import os
import io
import re
from pathlib import Path
from ruamel.yaml import YAML
from github import Github, InputGitAuthor

# Anchored to line starts so inline `:cl:` prose in a PR description
# (e.g. "PRs without :cl: blocks ...") does not get parsed as a block —
# previously the unanchored form captured trailing prose as the author
# string, which corrupted .all_changelog.yml (see PR #109 incident).
CL_BODY = re.compile(r"^:cl:[ \t]*(.+)?\r?\n((?:.|\n|\r)*?)\r?\n^/:cl:[ \t]*$", re.MULTILINE)
CL_SPLIT = re.compile(r"(^\w+):\s+(\w.+)", re.MULTILINE)

git_email = os.getenv("GIT_EMAIL")
git_name = os.getenv("GIT_NAME")

# Blessed is the GoOnStAtIoN birb ZeWaKa for thinking of this first
repo = os.getenv("GITHUB_REPOSITORY")
token = os.getenv("GITHUB_TOKEN")
sha = os.getenv("GITHUB_SHA")

git = Github(token)
repo = git.get_repo(repo)
commit = repo.get_commit(sha)
pr_list = commit.get_pulls()

if not pr_list.totalCount:
    print("Direct commit detected")
    exit(0) # Direct pushes to master (e.g. by GitHub Actions itself) have no PR; not an error.

pr = pr_list[0]

pr_body = pr.body
pr_number = pr.number
pr_author = pr.user.login

write_cl = {}
if pr_body is None:
    pr_body = ""
cl = CL_BODY.search(pr_body)
if cl is None:
    print("No CL found!")
    exit(0) # PRs without a :cl: block (or with the minimal :cl:\n/:cl: form) are a clean no-op, not a CI failure.
cl_list = CL_SPLIT.findall(cl.group(2) or "")


if cl.group(1) is not None:
    write_cl['author'] = cl.group(1).lstrip()
else:
    write_cl['author'] = pr_author

write_cl['delete-after'] = True

with open(Path.cwd().joinpath("tools/changelog/tags.yml")) as file:
    tags = YAML(typ='safe', pure=True).load(file)

write_cl['changes'] = []

for k, v in cl_list:
    if k in tags['tags'].keys(): # Check to see if there are any valid tags, as determined by tags.yml
        v = v.rstrip()
        if v not in list(tags['defaults'].values()): # Check to see if the tags are associated with something that isn't the default text
            write_cl['changes'].append({tags['tags'][k]: v})

if write_cl['changes']:
    with io.StringIO() as cl_contents:
        yaml_writer = YAML()
        yaml_writer.indent(sequence=4, offset=2)
        yaml_writer.dump(write_cl, cl_contents)
        cl_contents.seek(0)

        #Push the newly generated changelog to the master branch so that it can be compiled
        repo.create_file(f"html/changelogs/AutoChangeLog-pr-{pr_number}.yml", f"Automatic changelog generation for PR #{pr_number} [ci skip]", content=f'{cl_contents.read()}', branch='master', committer=InputGitAuthor(git_name, git_email))
    print("Done!")
else:
    print("No CL changes detected!")
    exit(0) # Change to a '1' if you want the action to count lacking CL changes as a failure
